kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: veientilarbeid
  namespace: {{ namespace }}
  labels:
    team: paw
  annotations:
    config.linkerd.io/proxy-memory-limit: "2048Mi"
    config.linkerd.io/proxy-memory-request: "512Mi"
    config.linkerd.io/proxy-cpu-limit: "1"
    config.linkerd.io/proxy-cpu-request: "200m"
spec:
  env:
  - name: APPRES_CMS_URL
    value: {{ appres_cms_url }}
  - name: LOGINSERVICE_URL
    value: {{ loginservice_url }}
  - name: VEIENTILARBEID_URL
    value: {{ veientilarbeid_url }}
  - name: AKTIVITETSPLAN_URL
    value: {{ aktivitetsplan_url }}
  - name: DIALOG_URL
    value: {{ dialog_url }}
  - name: DITTNAV_LINK_URL
    value: {{ dittnav_link_url }}
  - name: SYFOFRONT_URL
    value: {{ syfofront_url }}
  - name: VEIVISERSOSIALHJELP_URL
    value: {{ veivisersosialhjelp_url }}
  - name: ARBEIDSPLASSEN_URL
    value: {{ arbeidsplassen_url }}
  - name: BEHOVSVURDERING_URL
    value: {{ behovsvurdering_url }}
  - name: START_SAMTALE_URL
    value: {{ start_samtale_url }}
  - name: ARBEIDSSOKERREGISTRERING_URL
    value: {{ arbeidssokerregistrering_url }}
  - name: VEILARBPROXY_URL
    value: {{ veilarbproxy_url }}
  - name: FASIT_ENVIRONMENT_NAME
    value: {{ app_environment_name }}
  - name: DISABLE_FRONTEND_LOGGER
    value: 'true'
  - name: DISABLE_SENSU_METRICS
    value: 'true'
  - name: FORTSETT_DP_SOKNAD_URL
    value: {{ fortsettDpSoknadUrl }}
  - name: FORTSETT_NY_DP_SOKNAD_URL
    value: {{ fortsettNyDpSoknadUrl }}
  envFrom:
    - configmap: loginservice-idporten
  image: {{image}}
  {{#if ingresses}}
  ingresses:
  {{#each ingresses as |url|}}
     - {{url}}
  {{/each}}
  {{/if}}
  liveness:
    path: /isAlive
    port: 8080
    initialDelay: 60
  port: 8080
  prometheus:
    enabled: false
    path: /internal/metrics
  readiness:
    path: /isReady
    port: 8080
    initialDelay: 60
  replicas:
    min: 1
    max: 2
  webproxy: true
  accessPolicy:
    outbound:
      rules:
        - application: pto-proxy
          namespace: pto
      external:
      {{#each externalHosts as |host|}}
         - host: {{host}}
      {{/each}}
