kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: veientilarbeid
  namespace: {{ namespace }}
  labels:
    team: paw
spec:
  env:
  - name: APPRES_CMS_URL
    value: {{ appres_cms_url }}
  - name: AAD_B2C_CLIENTID_USERNAME
    value: {{ LOGINSERVICE_IDPORTEN_AUDIENCE }}
  - name: AAD_B2C_DISCOVERY_URL
    value: {{ LOGINSERVICE_IDPORTEN_DISCOVERY_URL }}
  - name: LOGINSERVICE_URL
    value: {{ loginservice_url }}
  - name: VEIENTILARBEID_URL
    value: {{ veientilarbeid_url }}
  - name: AKTIVITETSPLAN_URL
    value: {{ aktivitetsplan_url }}
  - name: DIALOG_URL
    value: {{ dialog_url }}
  - name: VEIVISERARBEIDSSOKER_URL
    value: {{ veiviserarbeidssoker_url }}
  - name: VEILEDEARBEIDSSOKER_URL
    value: {{ veiledearbeidssoker_url }}
  - name: JOBBSOKERKOMPETANSE_URL
    value: {{ jobbsokerkompetanse_url }}
  - name: DITTNAV_LINK_URL
    value: {{ dittnav_link_url }}
  - name: SYFOFRONT_URL
    value: {{ syfofront_url }}
  - name: VEIVISERSOSIALHJELP_URL
    value: {{ veivisersosialhjelp_url }}
  - name: ARBEIDSPLASSEN_URL
    value: {{ arbeidsplassen_url }}
  - name: BEHOVSVURDERING_URL
    value: {{ behovsvurdering_url }}
  - name: START_SAMTALE_URL
    value: {{ start_samtale_url }}
  - name: ENDRE_SITUASJON_URL
    value: {{ endre_situasjon_url }}
  - name: ARBEIDSSOKERREGISTRERING_URL
    value: {{ arbeidssokerregistrering_url }}
  - name: VEILARBPROXY_URL
    value: {{ veilarbproxy_url }}
  - name: FRONTENDLOGGER_URL
    value: {{ frontendlogger_url }}
  - name: FASIT_ENVIRONMENT_NAME
    value: {{ app_environment_name }}
  envFrom:
    - configMap: loginservice-idporten
  image: {{image}}
  ingresses:
  {{#each ingresses as |url|}}
     - {{url}}
  {{/each}}
  liveness:
    path: /internal/isAlive
    port: 8080
    initialDelay: 20
  port: 8080
  prometheus:
    enabled: true
    path: /internal/metrics
  readiness:
    path: /internal/isReady
    port: 8080
    initialDelay: 20
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: "3"
      memory: 2048Mi
    requests:
      memory: 1024Mi
      cpu: "1"
  webproxy: true
