export const sporsmalMap = {
    utdanning: 'Hva er din høyeste fullførte utdanning?',
    utdanningBestatt: 'Er utdanningen din bestått?',
    utdanningGodkjent: 'Er utdanningen din godkjent i Norge?',
    helseHinder: 'Har du helseproblemer som hindrer deg i å søke eller være i jobb?',
    andreForhold: 'Har du andre problemer med å søke eller være i jobb?',
    sisteStilling: 'Hva er din siste jobb?',
    dinSituasjon: 'Hvilken jobbsituasjon passer best?',
    fremtidigSituasjon: 'Hva tenker du om din fremtidige situasjon?',
    tilbakeIArbeid: 'Tror du at du kommer tilbake i jobb før du har vært sykmeldt i 52 uker?',
};

export const svarMap = {
    utdanning: {
        INGEN_UTDANNING: 'Ingen utdanning',
        GRUNNSKOLE: 'Grunnskole',
        VIDEREGAENDE_GRUNNUTDANNING: 'Videregående grunnutdanning (1 til 2 år)',
        VIDEREGAENDE_FAGBREV_SVENNEBREV: 'Videregående, fagbrev eller svennebrev (3 år eller mer)',
        HOYERE_UTDANNING_1_TIL_4: 'Høyere utdanning (1 til 4 år)',
        HOYERE_UTDANNING_5_ELLER_MER: 'Høyere utdanning (5 år eller mer)',
    },
    utdanningBestatt: {
        JA: 'Ja',
        NEI: 'Nei',
    },
    utdanningGodkjent: {
        JA: 'Ja',
        NEI: 'Nei',
        VET_IKKE: 'Vet ikke',
    },
    helseHinder: {
        JA: 'Ja',
        NEI: 'Nei',
    },
    andreForhold: {
        JA: 'Ja',
        NEI: 'Nei',
    },
    sisteStilling: {
        HAR_HATT_JOBB: 'Har vært i jobb',
        HAR_IKKE_HATT_JOBB: 'Har ikke vært i jobb',
        INGEN_SVAR: 'Ikke besvart',
    },
    dinSituasjon: {
        MISTET_JOBBEN: 'Har mistet eller kommer til å miste jobben',
        HAR_SAGT_OPP: 'Har sagt opp eller kommer til å si opp',
        DELTIDSJOBB_VIL_MER: 'Har deltidsjobb, men vil jobbe mer',
        ALDRI_HATT_JOBB: 'Har aldri vært i jobb',
        VIL_BYTTE_JOBB: 'Har jobb, men vil bytte',
        JOBB_OVER_2_AAR: 'Har ikke vært i jobb de siste 2 årene',
        ER_PERMITTERT: 'Er permittert eller kommer til å bli permittert',
        USIKKER_JOBBSITUASJON: 'Er usikker på jobbsituasjonen min',
        AKKURAT_FULLFORT_UTDANNING: 'Har akkurat fullført utdanning, militærtjeneste eller annet',
        VIL_FORTSETTE_I_JOBB: 'Har jobb og ønsker å fortsette i den jobben jeg er i',
        OPPSIGELSE: 'Jeg har blitt sagt opp av arbeidsgiver',
        ENDRET_PERMITTERINGSPROSENT: 'Arbeidsgiver har endret permitteringen min',
        TILBAKE_TIL_JOBB: 'Jeg skal begynne å jobbe igjen hos min arbeidsgiver',
        NY_JOBB: 'Jeg skal begynne å jobbe hos en annen arbeidsgiver',
        MIDLERTIDIG_JOBB: 'Jeg har fått midlertidig jobb hos en annen arbeidsgiver',
        KONKURS: 'Arbeidsgiveren min er konkurs',
        SAGT_OPP: 'Jeg har sagt opp jobben min',
        ANNET: 'Ingen av situasjonene passer for meg',
    },
    fremtidigSituasjon: {
        SAMME_ARBEIDSGIVER: 'Jeg skal tilbake til jobben jeg har',
        SAMME_ARBEIDSGIVER_NY_STILLING: 'Jeg skal tilbake til arbeidsgiveren min, men i ny stilling',
        NY_ARBEIDSGIVER: 'Jeg trenger ny jobb',
        USIKKER: 'Jeg er usikker',
        INGEN_PASSER: 'Ingen av disse alternativene passer',
    },
    tilbakeIArbeid: {
        JA_FULL_STILLING: 'Ja, i full stilling',
        JA_REDUSERT_STILLING: 'Ja, i redusert stilling',
        USIKKER: 'Usikker',
        NEI: 'Nei',
    },
};
