import { contextpathDittNav, erMikrofrontend } from '../utils/app-state-utils';

export const aktivitetsplanLenke = erMikrofrontend() ? `${contextpathDittNav}/aktivitetsplan` : '/aktivitetsplan';
export const dialogLenke = erMikrofrontend() ? `${contextpathDittNav}/aktivitetsplan/dialog` : '/aktivitetsplan/dialog';
export const stillingLenke = erMikrofrontend() ? `${contextpathDittNav}/arbeidsplassen/stillinger` : '/arbeidsplassen/stillinger';
export const cvLenke = erMikrofrontend() ? `${contextpathDittNav}/arbeidsplassen/cv` : '/arbeidsplassen/cv';
export const miaLenke = erMikrofrontend() ? `${contextpathDittNav}/mia` : '/mia';
export const veiviserarbeidssokerLenke = erMikrofrontend() ? `${contextpathDittNav}/veiviserarbeidssoker` : '/veiviserarbeidssoker';
export const jobbsokerkompetanseLenke = erMikrofrontend() ? `${contextpathDittNav}/jobbsokerkompetanse/resultatside` : '/jobbsokerkompetanse/resultatside';
export const tiltakinfoLenke = erMikrofrontend() ? `${contextpathDittNav}/tiltakinfo` : '/tiltakinfo';
export const sykefravaerLenke = erMikrofrontend() ? `${contextpathDittNav}/sykefravaer` : '/sykefravaer';
export const dagpengerLesmerLenke = erMikrofrontend() ? `${contextpathDittNav}/veiledearbeidssoker/mistet-jobben/dagpenger?sprak=nb` : '/veiledearbeidssoker/mistet-jobben/dagpenger?sprak=nb';
export const dagpengerSoknadLenke = 'https://www.nav.no/no/Person/Skjemaer-for-privatpersoner/Skjemaer/Uten+arbeid/Dagpenger';
export const sosialhjelpLenke = erMikrofrontend() ? `${contextpathDittNav}/veivisersosialhjelp` : '/veivisersosialhjelp';
export const behovsvurderingLenke = erMikrofrontend() ? `${contextpathDittNav}/behovsvurdering` : '/behovsvurdering';
export const motestotteLenke = erMikrofrontend() ? `${contextpathDittNav}/forberede-moete` : '/forberede-moete';
export const reaktiveringLenke = erMikrofrontend() ? `${contextpathDittNav}/arbeidssokerregistrering/start` : '/arbeidssokerregistrering/start';
export const sykepengerLenke = 'https://www.nav.no/no/Person/Arbeid/Sykmeldt%2C+arbeidsavklaringspenger+og+yrkesskade/Sykepenger/Sykepenger+til+arbeidstakere#chapter-7';
export const meldekortLenke = 'https://tjenester.nav.no/meldekort/genereltommeldekort/';
export const aapSoknadLenke = 'https://www.nav.no/no/Person/Skjemaer-for-privatpersoner/Skjemaer/Arbeid%2C+helse+og+sykdom/arbeidsavklaringspenger';
export const difiLenke = 'https://brukerprofil.difi.no/minprofil/';